//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Win8InstallTool.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Win8InstallTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 shellex\ContextMenuHandlers\Compatibility
        ///执行文件 - 兼容性疑难解答
        ///出了问题不去谷歌，看这解答有个卵用
        ///exefile
        ///
        ///shellex\ContextMenuHandlers\Library Location
        ///文件夹 - 包含到库中
        ///我现在还没用过这个系统自带的各种库文件夹，删了吧
        ///Folder
        ///
        ///shellex\ContextMenuHandlers\{90AA3A4E-1CBA-4233-B8BB-535773D48449}
        ///所有文件 - 固定到任务栏
        ///直接往任务栏上拖即可
        ///*
        ///
        ///shell\AnyCode
        ///文件夹及其背景 - Open with Visual Studio
        ///没啥用纯看着碍眼
        ///Directory
        ///Directory\background
        ///
        ///shell\edit
        ///各种纯文本类文件 - 编辑
        ///跟&quot;记事本打开&quot;的功能重复了，删之
        ///cmdfile
        ///batfile
        ///xmlfile
        ///regfile
        ///SystemFileAssociations\text
        ///
        ///Shell\setdesktopwallpaper
        ///各种媒体文件 - 设为桌面背景
        ///一般在播放器里都 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ContextMenuRules {
            get {
                return ResourceManager.GetString("ContextMenuRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Ext
        ///DisableAddonLoadTimePerformanceNotifications
        ///1
        ///关闭IE加载项性能通知
        ///防止出现打开IE浏览器状态栏提示关闭加载项来提高浏览器运行速度的提示
        ///
        ///HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Internet Explorer\Suggested Sites
        ///Enabled
        ///0
        ///IE打开建议的网站
        ///建议你妈逼，老子看啥要你指点？
        ///
        ///HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Internet Explorer\Main
        ///DisableFirstRunCustomize
        ///1
        ///禁用首次运行向导
        ///全是没卵用的配置，浪费启动时间
        ///
        ///HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer
        ///NoDriveTypeAutoRun
        ///255
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string GroupPolicyRules {
            get {
                return ResourceManager.GetString("GroupPolicyRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用性能计数器
        ///统计系统底层性能的东西，一般人用不到，还老是在日志里报错 “无法打开服务器服务性能对象……”
        ///DisablePerfCounter
        ///
        ///关闭 SChannel 事件日志
        ///屏蔽系统日志里的 &apos;从远程终点接收到一个严重警告&apos; 错误
        ///DisableSchannelLog
        ///
        ///禁用已经过时的SSL系列协议
        ///SSL协议已经被TLS所淘汰，在Windows10系统中默认被禁用，这些功能不应该再被使用。
        ///DisableSSL
        ///
        ///禁用TLS1.0和RC4协议
        ///这俩协议存在安全漏洞且已经被更新的标准所替代，建议禁用，但要注意仍有一些古老的软件使用它们。
        ///DisableTLS1_0
        ///
        ///增强IE浏览器安全性
        ///具体操作包括：禁用过时的SSL协议，启用增强的保护功能，禁用友好错误信息。
        ///IESecurity
        ///
        ///禁止系统失败后写入调试信息
        ///不做系统相关开发的话这些调试信息鸟用没有，如果禁用了虚拟内存还会在事件日志里报错
        ///DisableCrashDump
        /// 的本地化字符串。
        /// </summary>
        internal static string RegistryRules {
            get {
                return ResourceManager.GetString("RegistryRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 # 发传真的那个关闭系统功能后会自动删除。
        ///
        ///Compressed (zipped) Folder.ZFSendToTarget
        ///有专门压缩软件来做了
        ///
        ///Mail Recipient.MAPIMail
        ///邮件这么正式的东西还是不用这么快捷的方法
        ///
        ///文档.mydocs
        ///就是个直接复制到用户的文档目录，可惜我不用它
        /// 的本地化字符串。
        /// </summary>
        internal static string SendToRules {
            get {
                return ResourceManager.GetString("SendToRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BFE
        ///Windows安全平台的核心服务，防火墙和杀毒软件都需要，如果不用它们倒是可以关了
        ///Disabled
        ///
        ///hidserv
        ///不用特殊输入设备的不需要，该服务还容易被攻击者利用
        ///Disabled
        ///
        ///ShellHWDetection
        ///这年头谁还玩光盘自动播放，该服务还容易被攻击者利用
        ///Disabled
        ///
        ///LanmanServer
        ///服务器文件共享才需要，家用机可以关掉
        ///Disabled
        ///
        ///LanmanWorkstation
        ///用SMB协议做文件共享的服务，办公室可能需要，不用的话可以关掉
        ///Disabled
        ///
        ///lmhosts
        ///办公室远程控制打印机、文件才需要
        ///Disabled
        ///
        ///WSearch
        ///系统自带的搜索功能，并不是每个人都需要，还耗磁盘
        ///Disabled
        ///
        ///PcaSvc
        ///啥卵用都没有的兼容性助手
        ///Disabled
        ///
        ///IKEEXT
        ///某些协议的VPN需要这个服务，不用的话可以关掉
        ///Disabled
        ///
        ///WPDBusEnum
        ///反正我是没用过什么可移动大容量存储设备
        ///Disabled
        ///
        ///TrkWks
        ///没几个人会把NTFS文件链接到远程计算机
        ///Disabled
        ///
        ///PolicyAgent
        ///关掉后防火墙不能使用IPSec策略 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ServiceRules {
            get {
                return ResourceManager.GetString("ServiceRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Microsoft Office 2016 工具
        ///我从来不用的东西
        ///
        ///Music, Photos and Videos
        ///我从来不用的东西
        ///
        ///WinRAR
        ///相关功能都在右键菜单里，没必要再去开始菜单占个位置
        /// 的本地化字符串。
        /// </summary>
        internal static string StartupRules {
            get {
                return ResourceManager.GetString("StartupRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Microsoft\Windows\Application Experience
        ///客户体验改善计划相关的任务，没同意的可以删了
        ///
        ///Microsoft\Windows\Autochk
        ///客户体验改善计划相关的任务，没同意的可以删了
        ///
        ///Microsoft\Windows\Customer Experience Improvement Program
        ///全是客户体验改善计划，不参加的直接删光光
        ///
        ///Microsoft\Windows\Application Experience\StartupAppTask
        ///启动项应该自己注意，而不是靠它来扫描
        ///:DISABLE
        ///
        ///Microsoft\Windows\DiskCleanup\SilentCleanup
        ///什么傻逼任务，磁盘空间不足还用你来提示？？？
        ///:DISABLE
        ///
        ///Microsoft\Windows\SkyDrive
        ///SkyDrive 目录里两个同步任务是万恶之源，老在日志里报错，不用就删掉
        ///
        ///Microsoft\Windows\UPnP\UPnPHostConfig
        ///用不用 UPnp 服务不是你说了算，还敢在后台偷偷改
        ///:DISABLE
        ///
        ///Microsoft\Offi [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string TaskSchdulerRules {
            get {
                return ResourceManager.GetString("TaskSchdulerRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 优化资源管理器选项
        ///显示文件扩展名、自动扩展到当前目录、不现实库和收藏夹等，优化后需要在资源管理器里刷新一下。
        ///ExplorerOptions
        ///
        ///禁用键盘辅助功能
        ///就是禁用筛选键、粘滞键、鼠标键、切换键这些东西，屁用没有，一不小心就按出来相当烦人。
        ///KeyboardA11y
        /// 的本地化字符串。
        /// </summary>
        internal static string UserRegistryRules {
            get {
                return ResourceManager.GetString("UserRegistryRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 增加 ReadyBoot 日志文件大小
        ///增加日志文件上限到40MB，解决事件日志里 Circular Kernel Context Logger 停止的问题
        ///HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\WMI\Autologger\ReadyBoot
        ///null
        ///40
        ///
        ///启用 AirSpaceChannel 日志文件循环选项
        ///解决日志文件溢满导致 EventLog-AirSpaceChannel 已停止的问题
        ///HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\WMI\Autologger\EventLog-AirSpaceChannel
        ///true
        ///null
        /// 的本地化字符串。
        /// </summary>
        internal static string WMILoggerRules {
            get {
                return ResourceManager.GetString("WMILoggerRules", resourceCulture);
            }
        }
    }
}
